
CREATE DATABASE league_of_legends;
USE league_of_legends;

CREATE TABLE champions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    role VARCHAR(50) NOT NULL,
    difficulty INT NOT NULL,
    description TEXT
);

CREATE TABLE jungle_monsters (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    spawn_time INT NOT NULL,
    respawn_time INT NOT NULL,
    description TEXT
);

CREATE TABLE items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    item_id INT NOT NULL,
    name VARCHAR(100) NOT NULL,
    cost INT NOT NULL,
    stats TEXT,
    description TEXT
);

INSERT INTO champions (name, role, difficulty, description)
VALUES
('Aatrox', 'Fighter', 3, 'The Darkin Blade'),
('Ahri', 'Mage', 2, 'The Nine-Tailed Fox'),
('Akali', 'Assassin', 3, 'The Rogue Assassin'),
('Alistar', 'Tank', 2, 'The Minotaur'),
('Amumu', 'Tank', 1, 'The Sad Mummy'),
('Anivia', 'Mage', 3, 'The Cryophoenix'),
('Annie', 'Mage', 1, 'The Dark Child'),
('Aphelios', 'Marksman', 4, 'The Weapon of the Faithful'),
('Ashe', 'Marksman', 1, 'The Frost Archer'),
('Aurelion Sol', 'Mage', 2, 'The Star Forger'),
('Azir', 'Mage', 3, 'The Emperor of the Sands'),
('Bard', 'Support', 3, 'The Wandering Caretaker'),
('Blitzcrank', 'Tank', 1, 'The Great Steam Golem'),
('Brand', 'Mage', 2, 'The Burning Vengeance'),
('Braum', 'Support', 1, 'The Heart of the Freljord'),
('Caitlyn', 'Marksman', 2, 'The Sheriff of Piltover'),
('Camille', 'Fighter', 3, 'The Steel Shadow'),
('Cassiopeia', 'Mage', 3, 'The Serpent\'s Embrace'),
('Cho\'Gath', 'Tank', 2, 'The Terror of the Void'),
('Corki', 'Marksman', 2, 'The Daring Bombardier'),
('Darius', 'Fighter', 2, 'The Hand of Noxus'),
('Diana', 'Fighter', 2, 'Scorn of the Moon'),
('Dr. Mundo', 'Fighter', 1, 'The Madman of Zaun'),
('Draven', 'Marksman', 3, 'The Glorious Executioner'),
('Ekko', 'Assassin', 3, 'The Boy Who Shattered Time'),
('Elise', 'Mage', 3, 'The Spider Queen'),
('Evelynn', 'Assassin', 2, 'Agony\'s Embrace'),
('Ezreal', 'Marksman', 2, 'The Prodigal Explorer'),
('Fiddlesticks', 'Mage', 3, 'The Ancient Fear'),
('Fiora', 'Fighter', 3, 'The Grand Duelist'),
('Fizz', 'Assassin', 2, 'The Tidal Trickster'),
('Galio', 'Tank', 1, 'The Colossus'),
('Gangplank', 'Fighter', 3, 'The Saltwater Scourge'),
('Garen', 'Fighter', 1, 'The Might of Demacia'),
('Gnar', 'Fighter', 3, 'The Missing Link'),
('Gragas', 'Tank', 2, 'The Rabble Rouser'),
('Graves', 'Marksman', 2, 'The Outlaw'),
('Gwen', 'Fighter', 2, 'The Hallowed Seamstress'),
('Hecarim', 'Fighter', 2, 'The Shadow of War'),
('Heimerdinger', 'Mage', 2, 'The Revered Inventor'),
('Illaoi', 'Fighter', 2, 'The Kraken Priestess'),
('Irelia', 'Fighter', 3, 'The Blade Dancer'),
('Ivern', 'Support', 2, 'The Green Father'),
('Janna', 'Support', 1, 'The Storm\'s Fury'),
('Jarvan IV', 'Tank', 2, 'The Exemplar of Demacia'),
('Jax', 'Fighter', 2, 'Grandmaster at Arms'),
('Jayce', 'Fighter', 2, 'The Defender of Tomorrow'),
('Jhin', 'Marksman', 2, 'The Virtuoso'),
('Jinx', 'Marksman', 2, 'The Loose Cannon'),
('Kai\'Sa', 'Marksman', 2, 'Daughter of the Void'),
('Kalista', 'Marksman', 3, 'The Spear of Vengeance'),
('Karma', 'Support', 2, 'The Enlightened One'),
('Karthus', 'Mage', 3, 'The Deathsinger'),
('Kassadin', 'Assassin', 3, 'The Void Walker'),
('Katarina', 'Assassin', 3, 'The Sinister Blade'),
('Kayle', 'Fighter', 2, 'The Righteous'),
('Kayn', 'Assassin', 3, 'The Shadow Reaper'),
('Kennen', 'Mage', 2, 'The Heart of the Tempest'),
('Kha\'Zix', 'Assassin', 3, 'The Voidreaver'),
('Kindred', 'Marksman', 3, 'The Eternal Hunters'),
('Kled', 'Fighter', 3, 'The Cantankerous Cavalier'),
('Kog\'Maw', 'Marksman', 2, 'The Mouth of the Abyss'),
('LeBlanc', 'Mage', 3, 'The Deceiver'),
('Lee Sin', 'Fighter', 2, 'The Blind Monk'),
('Leona', 'Tank', 2, 'The Radiant Dawn'),
('Lillia', 'Fighter', 2, 'The Bashful Bloom'),
('Lissandra', 'Mage', 2, 'The Ice Witch'),
('Lucian', 'Marksman', 2, 'The Purifier'),
('Lulu', 'Support', 1, 'The Fae Sorceress'),
('Lux', 'Mage', 1, 'The Lady of Luminosity'),
('Malphite', 'Tank', 1, 'Shard of the Monolith'),
('Malzahar', 'Mage', 2, 'The Prophet of the Void'),
('Maokai', 'Tank', 1, 'The Twisted Treant'),
('Master Yi', 'Assassin', 1, 'The Wuju Bladesman'),
('Miss Fortune', 'Marksman', 1, 'The Bounty Hunter'),
('Mordekaiser', 'Fighter', 2, 'The Iron Revenant'),
('Morgana', 'Mage', 1, 'The Fallen'),
('Nami', 'Support', 2, 'The Tidecaller'),
('Nasus', 'Fighter', 1, 'The Curator of the Sands'),
('Nautilus', 'Tank', 2, 'The Titan of the Depths'),
('Neeko', 'Mage', 2, 'The Curious Chameleon'),
('Nidalee', 'Assassin', 3, 'The Bestial Huntress'),
('Nocturne', 'Assassin', 2, 'The Eternal Nightmare'),
('Nunu & Willump', 'Tank', 1, 'The Boy and His Yeti'),
('Olaf', 'Fighter', 1, 'The Berserker'),
('Orianna', 'Mage', 3, 'The Lady of Clockwork'),
('Ornn', 'Tank', 2, 'The Fire Below the Mountain'),
('Pantheon', 'Fighter', 2, 'The Unbreakable Spear'),
('Poppy', 'Tank', 2, 'Keeper of the Hammer'),
('Pyke', 'Support', 2, 'The Bloodharbor Ripper'),
('Qiyana', 'Assassin', 3, 'Empress of the Elements'),
('Quinn', 'Marksman', 2, 'Demacia\'s Wings'),
('Rakan', 'Support', 2, 'The Charmer'),
('Rammus', 'Tank', 1, 'The Armordillo'),
('Rek\'Sai', 'Fighter', 2, 'The Void Burrower'),
('Rell', 'Tank', 2, 'The Iron Maiden'),
('Renekton', 'Fighter', 2, 'The Butcher of the Sands'),
('Rengar', 'Assassin', 3, 'The Pridestalker'),
('Riven', 'Fighter', 2, 'The Exile'),
('Rumble', 'Fighter', 3, 'The Mechanized Menace'),
('Ryze', 'Mage', 3, 'The Rune Mage'),
('Samira', 'Marksman', 3, 'The Desert Rose'),
('Sejuani', 'Tank', 2, 'Fury of the North'),
('Senna', 'Marksman', 2, 'The Redeemer'),
('Seraphine', 'Mage', 1, 'The Starry-Eyed Songstress'),
('Sett', 'Fighter', 2, 'The Boss'),
('Shaco', 'Assassin', 3, 'The Demon Jester'),
('Shen', 'Tank', 2, 'The Eye of Twilight'),
('Shyvana', 'Fighter', 2, 'The Half-Dragon'),
('Singed', 'Tank', 2, 'The Mad Chemist'),
('Sion', 'Tank', 1, 'The Undead Juggernaut'),
('Sivir', 'Marksman', 1, 'The Battle Mistress'),
('Skarner', 'Fighter', 2, 'The Crystal Vanguard'),
('Sona', 'Support', 1, 'Maven of the Strings'),
('Soraka', 'Support', 1, 'The Starchild'),
('Swain', 'Mage', 3, 'The Noxian Grand General'),
('Sylas', 'Mage', 3, 'The Unshackled'),
('Syndra', 'Mage', 3, 'The Dark Sovereign'),
('Tahm Kench', 'Support', 2, 'The River King'),
('Taliyah', 'Mage', 2, 'The Stoneweaver'),
('Talon', 'Assassin', 2, 'The Blade\'s Shadow'),
('Taric', 'Support', 1, 'The Shield of Valoran'),
('Teemo', 'Marksman', 1, 'The Swift Scout'),
('Thresh', 'Support', 2, 'The Chain Warden'),
('Tristana', 'Marksman', 1, 'The Yordle Gunner'),
('Trundle', 'Fighter', 1, 'The Troll King'),
('Tryndamere', 'Fighter', 1, 'The Barbarian King'),
('Twisted Fate', 'Mage', 2, 'The Card Master'),
('Twitch', 'Marksman', 2, 'The Plague Rat'),
('Udyr', 'Fighter', 2, 'The Spirit Walker'),
('Urgot', 'Fighter', 2, 'The Dreadnought'),
('Varus', 'Marksman', 2, 'The Arrow of Retribution'),
('Vayne', 'Marksman', 2, 'The Night Hunter'),
('Veigar', 'Mage', 1, 'The Tiny Master of Evil'),
('Vel Koz', 'Mage', 2, 'The Eye of the Void'),
('Vex', 'Mage', 2, 'The Gloomist'),
('Vi', 'Fighter', 2, 'The Piltover Enforcer'),
('Viego', 'Assassin', 3, 'The Ruined King'),
('Viktor', 'Mage', 3, 'The Machine Herald'),
('Vladimir', 'Mage', 2, 'The Crimson Reaper'),
('Volibear', 'Fighter', 2, 'The Relentless Storm'),
('Warwick', 'Fighter', 1, 'The Uncaged Wrath of Zaun'),
('Wukong', 'Fighter', 2, 'The Monkey King'),
('Xayah', 'Marksman', 2, 'The Rebel'),
('Xerath', 'Mage', 3, 'The Magus Ascendant'),
('Xin Zhao', 'Fighter', 2, 'The Seneschal of Demacia'),
('Yasuo', 'Fighter', 3, 'The Unforgiven'),
('Yone', 'Fighter', 3, 'The Unforgotten'),
('Yorick', 'Fighter', 2, 'Shepherd of Souls'),
('Yuumi', 'Support', 1, 'The Magical Cat'),
('Zac', 'Tank', 2, 'The Secret Weapon'),
('Zed', 'Assassin', 3, 'The Master of Shadows'),
('Zeri', 'Marksman', 2, 'The Spark of Zaun'),
('Ziggs', 'Mage', 1, 'The Hexplosives Expert'),
('Zilean', 'Support', 2, 'The Chronokeeper'),
('Zoe', 'Mage', 2, 'The Aspect of Twilight'),
('Zyra', 'Mage', 2, 'Rise of the Thorns');

INSERT INTO jungle_monsters (name, spawn_time, respawn_time, description)
VALUES
('Blue Sentinel', 115, 300, 'A powerful jungle monster that provides a Crest of Insight buff upon defeat.'),
('Red Brambleback', 115, 300, 'A powerful jungle monster that provides a Crest of Cinders buff upon defeat.'),
('Gromp', 115, 150, 'A large toad-like monster that grants experience and gold.'),
('Murkwolf', 115, 120, 'A small pack of wolves that grants experience and gold.'),
('Raptor', 115, 150, 'A flock of small raptors that grants experience and gold.'),
('Krug', 115, 150, 'A pair of stone creatures that grant experience and gold when defeated.'),
('Rift Scuttler', 180, 135, 'A neutral monster that grants vision and a speed shrine upon defeat.'),
('Rift Herald', 480, 360, 'A powerful neutral monster that provides a buff to help push lanes when defeated.'),
('Baron Nashor', 1200, 420, 'The most powerful neutral monster in the game, grants a powerful team-wide buff when defeated.'),
('Dragon', 300, 300, 'A variety of elemental dragons that provide different buffs when defeated.'),
('Elder Dragon', 1200, 360, 'A more powerful version of the dragon that provides a significant buff to the team that defeats it.');

INSERT INTO items (item_id, name, cost, stats, description) VALUES
(3078, 'Trinity Force', 3333, 'Attack Damage: 30, Attack Speed: 30, Health: 200, Ability Haste: 20, Movement Speed: 5', 'Tons of Damage'),
(3153, 'Blade of the Ruined King', 3300, 'Attack Damage: 40, Attack Speed: 25, Life Steal: 12', 'Deals bonus physical damage on hit based on the targets current health.'),
(3031, 'Infinity Edge', 3400, 'Attack Damage: 70, Critical Strike Chance: 20', 'Increases critical strike damage.'),
(3046, 'Phantom Dancer', 2600, 'Attack Speed: 45, Critical Strike Chance: 20, Movement Speed: 7', 'Grants movement speed and attack speed when attacking.'),
(3072, 'The Bloodthirster', 3400, 'Attack Damage: 55, Life Steal: 20, Shield: 50-350', 'Grants a shield that absorbs damage when at full health.'),
(3087, 'Statikk Shiv', 2600, 'Attack Speed: 35, Critical Strike Chance: 20, Movement Speed: 5', 'Grants bonus magic damage on hit and chain lightning.'),
(3508, 'Essence Reaver', 2800, 'Attack Damage: 55, Critical Strike Chance: 20, Ability Haste: 20', 'Restores mana on hit.'),
(3142, 'Youmuus Ghostblade', 3000, 'Attack Damage: 60, Lethality: 18, Movement Speed: 7', 'Grants bonus movement speed and ghosting.'),
(3156, 'Maw of Malmortius', 3100, 'Attack Damage: 50, Magic Resist: 50, Life Line Shield: 350', 'Grants a shield that absorbs magic damage when health is low.'),
(3814, 'Edge of Night', 2900, 'Attack Damage: 50, Lethality: 10, Health: 325', 'Grants a spell shield that blocks the next enemy ability.'),
(3047, 'Plated Steelcaps', 1100, 'Armor: 20, Movement Speed: 45', 'Reduces incoming damage from basic attacks.'),
(3026, 'Guardian Angel', 2800, 'Attack Damage: 40, Armor: 40', 'Revives the champion upon death, restoring health and mana.'),
(3085, 'Runaans Hurricane', 2600, 'Attack Speed: 45, Critical Strike Chance: 20, Movement Speed: 7', 'Shoots additional bolts that deal physical damage.'),
(3022, 'Frozen Mallet', 3100, 'Attack Damage: 30, Health: 700', 'Basic attacks slow enemies.'),
(3748, 'Titanic Hydra', 3300, 'Attack Damage: 30, Health: 500, Health Regen: 150%', 'Deals bonus damage to nearby enemies.'),
(3102, 'Banshees Veil', 3000, 'Ability Power: 65, Magic Resist: 45, Health: 10', 'Grants a spell shield that blocks the next enemy ability.'),
(3194, 'Adaptive Helm', 2800, 'Health: 350, Magic Resist: 55, Health Regen: 100%, Cooldown Reduction: 10%', 'Reduces incoming magic damage from consecutive abilities.'),
(3165, 'Morellonomicon', 3000, 'Ability Power: 70, Health: 300', 'Grants Grievous Wounds on dealing magic damage.'),
(3124, 'Guinsoos Rageblade', 3100, 'Attack Damage: 40, Attack Speed: 25, Critical Strike Chance: 20', 'Grants on-hit effects with every third attack.'),
(3116, 'Rylais Crystal Scepter', 3000, 'Ability Power: 90, Health: 350', 'Spells slow enemies.'),
(3115, 'Nashors Tooth', 3000, 'Ability Power: 100, Attack Speed: 50', 'Basic attacks deal bonus magic damage.'),
(3157, 'Zhonyas Hourglass', 2900, 'Ability Power: 75, Armor: 45, Ability Haste: 10', 'Activate to become invulnerable and untargetable for 2.5 seconds.'),
(3110, 'Frozen Heart', 2700, 'Armor: 80, Mana: 400, Ability Haste: 20', 'Reduces attack speed of nearby enemies.'),
(3065, 'Spirit Visage', 2900, 'Health: 450, Magic Resist: 55, Health Regen: 100%, Ability Haste: 10', 'Increases healing effects.'),
(3068, 'Sunfire Aegis', 3200, 'Health: 450, Armor: 60, Magic Resist: 30, Ability Haste: 10', 'Deals magic damage to nearby enemies.'),
(3091, 'Wits End', 3100, 'Attack Speed: 40, Magic Resist: 50, On-Hit Damage: 50', 'Basic attacks deal bonus magic damage and restore health.'),
(3053, 'Steraks Gage', 3100, 'Attack Damage: 50, Health: 400', 'Grants a shield when taking large amounts of damage.'),
(3025, 'Iceborn Gauntlet', 2700, 'Armor: 65, Health: 400, Ability Haste: 20', 'Basic attacks create a slowing field.'),
(3193, 'Gargoyle Stoneplate', 3300, 'Armor: 60, Magic Resist: 60, Health: 0', 'Grants bonus health and resistances when taking multiple hits.'),
(3143, 'Randuins Omen', 2700, 'Armor: 80, Health: 250, Critical Strike Reduction: 20%', 'Reduces incoming damage from critical strikes.'),
(3083, 'Warmogs Armor', 3000, 'Health: 800, Health Regen: 200%, Ability Haste: 10', 'Restores health rapidly when out of combat.'),
(3109, 'Knights Vow', 2300, 'Health: 400, Armor: 40, Health Regen: 10%', 'Redirects damage taken by an allied champion.'),
(3050, 'Zekes Convergence', 2400, 'Health: 250, Armor: 25, Magic Resist: 25, Ability Haste: 20', 'Grants an aura that deals magic damage and slows enemies.'),
(3094, 'Rapid Firecannon', 2500, 'Attack Speed: 35, Critical Strike Chance: 20, Movement Speed: 7', 'Basic attacks gain bonus range and magic damage.'),
(3152, 'Hextech Rocketbelt', 3200, 'Ability Power: 90, Health: 350, Ability Haste: 15', 'Grants a dash that deals magic damage.'),
(3001, 'Abyssal Mask', 2700, 'Health: 350, Magic Resist: 55, Mana: 300, Ability Haste: 10', 'Nearby enemies take increased magic damage.'),
(3111, 'Mercurys Treads', 1100, 'Magic Resist: 25, Movement Speed: 45', 'Reduces duration of crowd control effects.'),
(3040, 'Seraphs Embrace', 3200, 'Ability Power: 80, Health: 250, Mana: 1000', 'Restores mana based on missing health or mana.'),
(3123, 'Executioners Calling', 800, 'Attack Damage: 15', 'Grants Grievous Wounds on dealing physical damage.');

SELECT * FROM items;